

GET http://localhost:3003/api/blogs HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdtYWlsIiwiaWQiOiI2MTQ1ODUwN2M2MDZmMDI1NzdiMmM2MmYiLCJpYXQiOjE2MzE5NTgyMjcsImV4cCI6MTYzMTk2MTgyN30.4dLn-nP8AVlo64zeh03OSziy9P-cHASSKVAFfVnQS1g

###

POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "test for users",
    "author": "Pasang",
    "url": "www.testforusers.com",
    "likes": 7
}

###

POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "test for users",
    "author": "Pasang",
    "url": "www.testforusers.com",
    "likes": 7,
    "userId":"61445e0cb270e11b90131401"
}

###

DELETE http://localhost:3003/api/blogs/6145922f90357ca9d90ec13b HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdtYWlsIiwiaWQiOiI2MTQ1ODUwN2M2MDZmMDI1NzdiMmM2MmYiLCJpYXQiOjE2MzE5NTgyMjcsImV4cCI6MTYzMTk2MTgyN30.4dLn-nP8AVlo64zeh03OSziy9P-cHASSKVAFfVnQS1g


###

PUT http://localhost:3003/api/blogs/6142edc0fa6b7c22908f5883 HTTP/1.1
content-type: application/json

{
    "likes": "111"
}

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdtYWlsIiwiaWQiOiI2MTQ1ODUwN2M2MDZmMDI1NzdiMmM2MmYiLCJpYXQiOjE2MzE5NDkyOTMsImV4cCI6MTYzMTk1Mjg5M30.4F47yWGFCuRDHiOMEFrr1f6sWkvDozytx6Kdd3FY1kE

{
    "title": "test this with bearer token",
    "author": "TokenTest",
    "url": "www.token.com",
    "likes": 7
    
}






