

GET http://localhost:3003/api/blogs HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdtYWlsIiwiaWQiOiI2MTQ1ODUwN2M2MDZmMDI1NzdiMmM2MmYiLCJpYXQiOjE2MzE5NTgyMjcsImV4cCI6MTYzMTk2MTgyN30.4dLn-nP8AVlo64zeh03OSziy9P-cHASSKVAFfVnQS1g

###

POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "gmail did it",
    "author": "Pasang",
    "url": "www.testforusers.com",
    "likes": 7,
    "comments": "this is test for comment"
}

###

POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "test for users",
    "author": "Pasang",
    "url": "www.testforusers.com",
    "likes": 7,
    "userId":"61445e0cb270e11b90131401"
}

###

DELETE http://localhost:3003/api/blogs/6145922f90357ca9d90ec13b HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdtYWlsIiwiaWQiOiI2MTQ1ODUwN2M2MDZmMDI1NzdiMmM2MmYiLCJpYXQiOjE2MzE5NTgyMjcsImV4cCI6MTYzMTk2MTgyN30.4dLn-nP8AVlo64zeh03OSziy9P-cHASSKVAFfVnQS1g


###

PUT http://localhost:3003/api/blogs/6142edc0fa6b7c22908f5883 HTTP/1.1
content-type: application/json

{
    "likes": "111"
}

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdtYWlsIiwiaWQiOiI2MTUyNDlmNmNlNWUwNzNlNzNlNGNmYjgiLCJpYXQiOjE2MzU3MjU2MTksImV4cCI6MTYzNTcyOTIxOX0.TmqJzQifhjqbOCRO3ppfXxQ1uTf_wx_1w7lMo4hVYSc

{
    "title": "gmail",
    "author": "comment test",
    "url": "www.comment.com",
    "likes": 7,
    "comment": "first comment"
    
}






